INSERT INTO 
    `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) 
VALUES 
    (1, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 1, 'bulanan'),
    (2, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 1, 'bulanan'),
    (3, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 1, 'bulanan'),
    (4, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 1, 'bulanan'),
    (5, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 1, 'bulanan'),
    (6, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 1, 'bulanan'),
    (7, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 1, 'bulanan'),
    (8, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 1, 'bulanan'),
    (9, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 1, 'bulanan'),
    (10, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 1, 'bulanan'),
    (11, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 1, 'bulanan'),
    (12, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Profesi', 1, 'bulanan'),
    (13, 'Panutan : Mampu memberikan teladan yang baik.', 'Profesi', 1, 'bulanan'),
    (14, 'Penentuan prioritas tugas : Menentukan prioritas tugas dengan tepat dan terstruktur.', 'Profesi', 1, 'bulanan'),
    (15, 'Pengambilan keputusan : Secara cepat dan tepat', 'Profesi', 1, 'bulanan'),
    (16, 'Memahami bawahan : mengetahui & mengukur kemampuan', 'Profesi', 1, 'bulanan'),
    (17, 'Motivator: menggerakkan & menggugah semangat bawahan.', 'Profesi', 1, 'bulanan'),
    (18, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 2, 'bulanan'),
    (19, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 2, 'bulanan'),
    (20, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 2, 'bulanan'),
    (21, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 2, 'bulanan'),
    (22, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 2, 'bulanan'),
    (23, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 2, 'bulanan'),
    (24, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 2, 'bulanan'),
    (25, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 2, 'bulanan'),
    (26, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 2, 'bulanan'),
    (27, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 2, 'bulanan'),
    (28, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 2, 'bulanan'),
    (29, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Profesi', 2, 'bulanan'),
    (30, 'Dokumentasi : Kelengkapan formulis asuhan keperawatan', 'Profesi', 2, 'bulanan'),
    (31, 'Kemandirian Implementasi Askep : meliputi monitoring pasien, terapi, pendelegasian serta mengkomunikasikan temuan - temuan penyimpangan status kesehatan pasien', 'Profesi', 2, 'bulanan'),
    (32, 'Ketuntasan penyelesaian masalah pasien : sesuai dengan perencanaan asuhan keperawatan / kebidanan yang telah dibuat', 'Profesi', 2, 'bulanan'),
    (33, 'Rasa empati : sikap dalam merespon masalah kesehatan pasien', 'Profesi', 2, 'bulanan'),
    (34, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 3, 'bulanan'),
    (35, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 3, 'bulanan'),
    (36, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 3, 'bulanan'),
    (37, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 3, 'bulanan'),
    (38, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 3, 'bulanan'),
    (39, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 3, 'bulanan'),
    (40, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 3, 'bulanan'),
    (41, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 3, 'bulanan'),
    (42, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 3, 'bulanan'),
    (43, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 3, 'bulanan'),
    (44, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 3, 'bulanan'),
    (45, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Profesi', 3, 'bulanan'),
    (46, 'Kemandirian Implementasi dalam melaksanan tugas: meliputi pendelegasian serta mengkomunikasikan temuan - temuan penyimpangan dalam pekerjaan.', 'Profesi', 3, 'bulanan'),
    (47, 'Ketuntasan penyelesaian masalah: sesuai dengan ketentuan yang telah dibuat.', 'Profesi', 3, 'bulanan'),
    (48, 'Rasa empati : sikap dalam merespon lingkungan sekitar', 'Profesi', 3, 'bulanan'),
    (49, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 4, 'bulanan'),
    (50, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 4, 'bulanan'),
    (51, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 4, 'bulanan'),
    (52, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 4, 'bulanan'),
    (53, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 4, 'bulanan'),
    (54, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 4, 'bulanan'),
    (55, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 4, 'bulanan'),
    (56, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 4, 'bulanan'),
    (57, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 4, 'bulanan'),
    (58, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 4, 'bulanan'),
    (59, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 4, 'bulanan'),
    (60, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Profesi', 4, 'bulanan'),
    (61, 'Kemandirian Implementasi dalam melaksanan tugas: meliputi pendelegasian serta mengkomunikasikan temuan - temuan penyimpangan dalam pekerjaan.', 'Profesi', 4, 'bulanan'),
    (62, 'Ketuntasan penyelesaian masalah: sesuai dengan ketentuan yang telah dibuat.', 'Profesi', 4, 'bulanan'),
    (63, 'Rasa empati : sikap dalam merespon lingkungan sekitar', 'Profesi', 4, 'bulanan'),
    (64, 'Wawasan keislaman : Mampu menjelaskan materi - materi ke-islaman', 'Ke-islaman', 1, 'tahunan'),
    (67, 'Praktik ibadah : Mampu Mempraktikkan ibadah praktis sesuai Tarjih Muhammadiyah', 'Ke-islaman', 1, 'tahunan'),
    (68, "Bacaan Al-Qur\'an : Baik dalam membaca Al-Qur\'an sesuai Tajwid", 'Ke-islaman', 1, 'tahunan'),
    (69, "Hafalan Al-Qur\'an: Baik dalam menghafal surat-surat Juz Amma sesuai Standart", 'Ke-islaman', 1, 'tahunan'),
    (70, 'Wawasan Ke-muhammadiyahan : baik dalam pemahaman wawasan ke-muhammadiyahan', 'Ke-muhammadiyahan', 1, 'tahunan'),
    (71, 'Keaktifan kajian RSU Muhammadiyah Metro', 'Ke-muhammadiyahan', 1, 'tahunan'),
    (72, 'Keaktifan di Persyarikatan dan Ortom', 'Ke-muhammadiyahan', 1, 'tahunan'),
    (73, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi  kerja', 1, 'tahunan'),
    (74, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi  kerja', 1, 'tahunan'),
    (75, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi  kerja', 1, 'tahunan'),
    (76, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi  kerja', 1, 'tahunan'),
    (77, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 1, 'tahunan'),
    (78, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 1, 'tahunan'),
    (79, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 1, 'tahunan'),
    (80, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 1, 'tahunan'),
    (81, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 1, 'tahunan'),
    (82, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 1, 'tahunan'),
    (83, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 1, 'tahunan'),
    (84, 'Kelengkapan Seragam Kerja : sesuai ketentan dan kelengkapan atribut', 'Kedisiplinan', 1, 'tahunan'),
    (85, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Kedisiplinan', 1, 'tahunan'),
    (86, 'Kehadiran Kerja', 'Kedisiplinan', 1, 'tahunan'),
    (87, 'Panutan : Mampu memberikan teladan yang baik.', 'Profesi', 1, 'tahunan'),
    (88, 'Penentuan prioritas tugas : Menentukan prioritas tugas dengan tepat dan terstruktur.', 'Profesi', 1, 'tahunan'),
    (89, 'Pengambilan keputusan : Secara cepat dan tepat', 'Profesi', 1, 'tahunan'),
    (90, 'Memahami bawahan : mengetahui & mengukur kemampuan', 'Profesi', 1, 'tahunan'),
    (91, 'Motivator: menggerakkan & menggugah semangat bawahan.', 'Profesi', 1, 'tahunan'),
    (92, 'Wawasan keislaman : Mampu menjelaskan materi - materi ke-islaman', 'Ke-islaman', 4, 'tahunan'),
    (93, 'Praktik ibadah : Mampu Mempraktikkan ibadah praktis sesuai Tarjih Muhammadiyah', 'Ke-islaman', 4, 'tahunan'),
    (94, "Bacaan Al-Qur\'an : Baik dalam membaca Al-Qur\'an sesuai Tajwid", 'Ke-islaman', 4, 'tahunan'),
    (95, "Hafalan Al-Qur\'an: Baik dalam menghafal surat-surat Juz Amma sesuai Standart", 'Ke-islaman', 4, 'tahunan'),
    (96, 'Wawasan Ke-muhammadiyahan : baik dalam pemahaman wawasan ke-muhammadiyahan', 'Ke-muhammadiyahan', 4, 'tahunan'),
    (97, 'Keaktifan kajian RSU Muhammadiyah Metro', 'Ke-muhammadiyahan', 4, 'tahunan'),
    (98, 'Keaktifan di Persyarikatan dan Ortom', 'Ke-muhammadiyahan', 4, 'tahunan'),
    (99, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 4, 'tahunan'),
    (100, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 4, 'tahunan'),
    (101, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 4, 'tahunan'),
    (102, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 4, 'tahunan'),
    (103, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 4, 'tahunan'),
    (104, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 4, 'tahunan'),
    (105, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 4, 'tahunan'),
    (106, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 4, 'tahunan'),
    (107, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 4, 'tahunan'),
    (108, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 4, 'tahunan'),
    (109, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 4, 'tahunan'),
    (110, 'Kelengkapan Seragam Kerja : sesuai ketentan dan kelengkapan atribut', 'Kedisiplinan', 4, 'tahunan'),
    (111, 'Kehadiran Kerja', 'Kedisiplinan', 4, 'tahunan'),
    (112, 'Pelaksanaan SPO : Persiapan pekerjaan dan sistematika kerja', 'Profesi', 4, 'tahunan'),
    (113, 'Kemandirian Implementasi dalam melaksanan tugas: meliputi pendelegasian serta mengkomunikasikan temuan - temuan penyimpangan dalam pekerjaan.', 'Profesi', 4, 'tahunan'),
    (114, 'Ketuntasan penyelesaian masalah: sesuai dengan ketentuan yang telah dibuat.', 'Profesi', 4, 'tahunan'),
    (115, 'Rasa empati : sikap dalam merespon lingkungan sekitar', 'Profesi', 4, 'tahunan'),
    (116, 'Wawasan keislaman : Mampu menjelaskan materi - materi ke-islaman', 'Ke-islaman', 3, 'tahunan'),
    (117, 'Praktik ibadah : Mampu Mempraktikkan ibadah praktis sesuai Tarjih Muhammadiyah', 'Ke-islaman', 3, 'tahunan'),
    (118, "Bacaan Al-Qur\'an : Baik dalam membaca Al-Qur\'an sesuai Tajwid", 'Ke-islaman', 3, 'tahunan'),
    (119, "Hafalan Al-Qur\'an: Baik dalam menghafal surat-surat Juz Amma sesuai Standart", 'Ke-islaman', 3, 'tahunan'),
    (120, 'Wawasan Ke-muhammadiyahan : baik dalam pemahaman wawasan ke-muhammadiyahan', 'Ke-muhammadiyahan', 3, 'tahunan'),
    (121, 'Keaktifan kajian RSU Muhammadiyah Metro', 'Ke-muhammadiyahan', 3, 'tahunan'),
    (122, 'Keaktifan di Persyarikatan dan Ortom', 'Ke-muhammadiyahan', 3, 'tahunan'),
    (123, 'Disiplin : kehadiran kerja tepat waktu', 'Prestasi Kerja', 3, 'tahunan'),
    (124, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi Kerja', 3, 'tahunan'),
    (125, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi Kerja', 3, 'tahunan'),
    (126, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi Kerja', 3, 'tahunan'),
    (127, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi Kerja', 3, 'tahunan'),
    (128, 'Membina hubungan pasien dan keluarga', 'Profesi', 3, 'tahunan'),
    (129, 'Komunikasi : Mengkomunikasikan aspirasi dan inisiatif', 'Profesi', 3, 'tahunan'),
    (130, 'Kolaborasi : Berkolaborasi dengan unit kerja terkait', 'Profesi', 3, 'tahunan'),
    (131, 'Pendidikan kepada pasien dan keluarga : tentang apa yang harus diketahui', 'Profesi', 3, 'tahunan'),
    (132, 'Kompetensi profesional', 'Profesi', 3, 'tahunan'),
    (133, 'Memahami uraian tugas profesinya', 'Profesi', 3, 'tahunan'),
    (134, 'Pelaksanan SPO : memahami dan melaksanakan SPO sesuai bidang', 'Profesi', 3, 'tahunan'),
    (135, 'Saling menghargai  : dalam tim pemberi asuhan', 'Profesi', 3, 'tahunan'),
    (136, 'Menerapkan/bersikap etik dalam menjalankan profesi', 'Profesi', 3, 'tahunan'),
    (137, 'Pendokumentasian kegiatan profesionalnya', 'Profesi', 3, 'tahunan'),
    (138, 'Monitoring dan evaluasi berdasarkan dokumentasi', 'Profesi', 3, 'tahunan'),
    (139, 'Identifikasi pasien : tepat dan benar', 'Profesi', 3, 'tahunan'),
    (140, 'Memahami dan melaksanakan komunikasi efektif  :  dengan pasien dan keluarga', 'Profesi', 3, 'tahunan'),
    (141, 'Menerapkan pencegahan resiko jatuh', 'Profesi', 3, 'tahunan'),
    (142, 'Ketepatan : dalam waktu dan peayanan', 'Profesi', 3, 'tahunan'),
    (143, 'Kepatuhan cuci tangan : sesuai prosedur', 'Profesi', 3, 'tahunan'),
    (144, 'Wawasan keislaman : Mampu menjelaskan materi - materi ke-islaman', 'Ke-islaman', 2, 'tahunan'),
    (145, 'Praktik ibadah : Mampu Mempraktikkan ibadah praktis sesuai Tarjih Muhammadiyah', 'Ke-islaman', 2, 'tahunan'),
    (146, "Bacaan Al-Qur\'an : Baik dalam membaca Al-Qur\'an sesuai Tajwid", 'Ke-islaman', 2, 'tahunan'),
    (147, "Hafalan Al-Qur\'an: Baik dalam menghafal surat-surat Juz Amma sesuai Standart", 'Ke-islaman', 2, 'tahunan'),
    (148, 'Wawasan Ke-muhammadiyahan : baik dalam pemahaman wawasan ke-muhammadiyahan', 'Ke-muhammadiyahan', 2, 'tahunan'),
    (149, 'Keaktifan kajian RSU Muhammadiyah Metro', 'Ke-muhammadiyahan', 2, 'tahunan'),
    (150, 'Keaktifan di Persyarikatan dan Ortom', 'Ke-muhammadiyahan', 2, 'tahunan'),
    (151, 'Disiplin : Kehadiran kerja tepat waktu', 'Sikap Kerja', 2, 'tahunan'),
    (152, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 2, 'tahunan'),
    (153, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 2, 'tahunan'),
    (154, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 2, 'tahunan'),
    (155, 'Melaksanakan pengkajian pasien pengkajian biopsikosial dan keagamaan', 'Kinerja Pelayanan', 2, 'tahunan'),
    (156, 'Identifikasi Keperawatan pasien : meliputi data dan dignosa', 'Kinerja Pelayanan', 2, 'tahunan'),
    (157, 'Merencanakan askep pasien : merencanakan dan menentukan askep lengkap, baik secara intervensinya secara keseluruhan', 'Kinerja Pelayanan', 2, 'tahunan'),
    (158, 'Membantu aktifitas pasien : melakukan dan memfasilitasi ADL pasien', 'Kinerja Pelayanan', 2, 'tahunan'),
    (159, 'Intervensi spesifikasi keperawatan dan terapi sesuai kondisi pasien', 'Kinerja Pelayanan', 2, 'tahunan'),
    (160, 'Evaluasi asuhan keperawatan', 'Kinerja Pelayanan', 2, 'tahunan'),
    (161, 'Membina hubungan pasien dan keluarga', 'Kinerja Pelayanan', 2, 'tahunan'),
    (162, 'Komunikasi : Mengkomunikasikan aspirasi dan inisiatif', 'Kinerja Pelayanan', 2, 'tahunan'),
    (163, 'Kolaborasi : Berkolaborasi dengan unit kerja terkait', 'Kinerja Pelayanan', 2, 'tahunan'),
    (164, 'Pendidikan kepada pasien dan keluarga : tentang apa yang harus diketahui', 'Kinerja Pelayanan', 2, 'tahunan'),
    (165, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Mutu Pelayanan', 2, 'tahunan'),
    (166, 'Pemahaman pasien sesuai edukasi perawat', 'Mutu Pelayanan', 2, 'tahunan'),
    (167, 'Pengkajian pasien resiko jatuh', 'Mutu Pelayanan', 2, 'tahunan'),
    (168, 'Kesalahan pemberian obat : sesuai prosedur 6 benar serta pelaporannya', 'Mutu Pelayanan', 2, 'tahunan');
