INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (1, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (2, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (3, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (4, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (5, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (6, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (7, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (8, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (9, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (10, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (11, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (12, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Profesi', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (13, 'Panutan : Mampu memberikan teladan yang baik.', 'Profesi', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (14, 'Penentuan prioritas tugas : Menentukan prioritas tugas dengan tepat dan terstruktur.', 'Profesi', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (15, 'Pengambilan keputusan : Secara cepat dan tepat', 'Profesi', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (16, 'Memahami bawahan : mengetahui & mengukur kemampuan', 'Profesi', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (17, 'Motivator: menggerakkan & menggugah semangat bawahan.', 'Profesi', 1, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (18, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (19, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (20, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (21, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (22, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (23, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (24, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (25, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (26, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (27, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (28, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (29, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Profesi', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (30, 'Dokumentasi : Kelengkapan formulis asuhan keperawatan', 'Profesi', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (31, 'Kemandirian Implementasi Askep : meliputi monitoring pasien, terapi, pendelegasian serta mengkomunikasikan temuan - temuan penyimpangan status kesehatan pasien', 'Profesi', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (32, 'Ketuntasan penyelesaian masalah pasien : sesuai dengan perencanaan asuhan keperawatan / kebidanan yang telah dibuat', 'Profesi', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (33, 'Rasa empati : sikap dalam merespon masalah kesehatan pasien', 'Profesi', 2, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (34, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (35, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (36, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (37, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (38, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (39, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (40, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (41, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (42, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (43, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (44, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (45, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Profesi', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (46, 'Kemandirian Implementasi dalam melaksanan tugas: meliputi pendelegasian serta mengkomunikasikan temuan - temuan penyimpangan dalam pekerjaan.', 'Profesi', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (47, 'Ketuntasan penyelesaian masalah: sesuai dengan ketentuan yang telah dibuat.', 'Profesi', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (48, 'Rasa empati : sikap dalam merespon lingkungan sekitar', 'Profesi', 3, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (49, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (50, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (51, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (52, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (53, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (54, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (55, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (56, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (57, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (58, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (59, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (60, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Profesi', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (61, 'Kemandirian Implementasi dalam melaksanan tugas: meliputi pendelegasian serta mengkomunikasikan temuan - temuan penyimpangan dalam pekerjaan.', 'Profesi', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (62, 'Ketuntasan penyelesaian masalah: sesuai dengan ketentuan yang telah dibuat.', 'Profesi', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (63, 'Rasa empati : sikap dalam merespon lingkungan sekitar', 'Profesi', 4, 'bulanan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (64, 'Wawasan keislaman : Mampu menjelaskan materi - materi ke-islaman', 'Ke-islaman', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (67, 'Praktik ibadah : Mampu Mempraktikkan ibadah praktis sesuai Tarjih Muhammadiyah', 'Ke-islaman', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (68, 'Bacaan Al-Qur\'an : Baik dalam membaca Al-Qur\'an sesuai Tajwid', 'Ke-islaman', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (69, 'Hafalan Al-Qur\'an: Baik dalam menghafal surat-surat Juz Amma sesuai Standart', 'Ke-islaman', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (70, 'Wawasan Ke-muhammadiyahan : baik dalam pemahaman wawasan ke-muhammadiyahan', 'Ke-muhammadiyahan', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (71, 'Keaktifan kajian RSU Muhammadiyah Metro', 'Ke-muhammadiyahan', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (72, 'Keaktifan di Persyarikatan dan Ortom', 'Ke-muhammadiyahan', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (73, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi  kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (74, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi  kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (75, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi  kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (76, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi  kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (77, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (78, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (79, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (80, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (81, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (82, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (83, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (84, 'Kelengkapan Seragam Kerja : sesuai ketentan dan kelengkapan atribut', 'Kedisiplinan', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (85, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Kedisiplinan', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (86, 'Kehadiran Kerja', 'Kedisiplinan', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (87, 'Panutan : Mampu memberikan teladan yang baik.', 'Profesi', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (88, 'Penentuan prioritas tugas : Menentukan prioritas tugas dengan tepat dan terstruktur.', 'Profesi', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (89, 'Pengambilan keputusan : Secara cepat dan tepat', 'Profesi', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (90, 'Memahami bawahan : mengetahui & mengukur kemampuan', 'Profesi', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (91, 'Motivator: menggerakkan & menggugah semangat bawahan.', 'Profesi', 1, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (92, 'Wawasan keislaman : Mampu menjelaskan materi - materi ke-islaman', 'Ke-islaman', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (93, 'Praktik ibadah : Mampu Mempraktikkan ibadah praktis sesuai Tarjih Muhammadiyah', 'Ke-islaman', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (94, 'Bacaan Al-Qur\'an : Baik dalam membaca Al-Qur\'an sesuai Tajwid', 'Ke-islaman', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (95, 'Hafalan Al-Qur\'an: Baik dalam menghafal surat-surat Juz Amma sesuai Standart', 'Ke-islaman', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (96, 'Wawasan Ke-muhammadiyahan : baik dalam pemahaman wawasan ke-muhammadiyahan', 'Ke-muhammadiyahan', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (97, 'Keaktifan kajian RSU Muhammadiyah Metro', 'Ke-muhammadiyahan', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (98, 'Keaktifan di Persyarikatan dan Ortom', 'Ke-muhammadiyahan', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (99, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (100, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (101, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (102, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (103, 'Ketelitian : Meminimalisir kesalahan dalam bekerja.', 'Sikap Kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (104, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (105, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (106, 'Koordinasi : Berkoordinasi dengan unit kerja terkait', 'Sikap Kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (107, 'Ketaatan perintah tugas : Melaksanakan perintah tugas', 'Sikap Kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (108, 'Tanggung jawab: baik dalam mengakui kesalahan, dan bersedia menanggung resiko atas kesalahan.', 'Sikap Kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (109, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (110, 'Kelengkapan Seragam Kerja : sesuai ketentan dan kelengkapan atribut', 'Kedisiplinan', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (111, 'Kehadiran Kerja', 'Kedisiplinan', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (112, 'Pelaksanaan SPO : Persiapan pekerjaan dan sistematika kerja', 'Profesi', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (113, 'Kemandirian Implementasi dalam melaksanan tugas: meliputi pendelegasian serta mengkomunikasikan temuan - temuan penyimpangan dalam pekerjaan.', 'Profesi', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (114, 'Ketuntasan penyelesaian masalah: sesuai dengan ketentuan yang telah dibuat.', 'Profesi', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (115, 'Rasa empati : sikap dalam merespon lingkungan sekitar', 'Profesi', 4, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (116, 'Wawasan keislaman : Mampu menjelaskan materi - materi ke-islaman', 'Ke-islaman', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (117, 'Praktik ibadah : Mampu Mempraktikkan ibadah praktis sesuai Tarjih Muhammadiyah', 'Ke-islaman', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (118, 'Bacaan Al-Qur\'an : Baik dalam membaca Al-Qur\'an sesuai Tajwid', 'Ke-islaman', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (119, 'Hafalan Al-Qur\'an: Baik dalam menghafal surat-surat Juz Amma sesuai Standart', 'Ke-islaman', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (120, 'Wawasan Ke-muhammadiyahan : baik dalam pemahaman wawasan ke-muhammadiyahan', 'Ke-muhammadiyahan', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (121, 'Keaktifan kajian RSU Muhammadiyah Metro', 'Ke-muhammadiyahan', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (122, 'Keaktifan di Persyarikatan dan Ortom', 'Ke-muhammadiyahan', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (123, 'Disiplin : kehadiran kerja tepat waktu', 'Prestasi Kerja', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (124, 'Hasil kerja : Baik dalam kualitas maupun kuantitas', 'Prestasi Kerja', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (125, 'Pengetahuan pekerjaan : Mengetahui bidang tugasnya', 'Prestasi Kerja', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (126, 'Kemandirian : pekerjaan yang bersifat rutin maupun khusus', 'Prestasi Kerja', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (127, 'Penyelesaian tugas : baik dan tepat waktu', 'Prestasi Kerja', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (128, 'Membina hubungan pasien dan keluarga', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (129, 'Komunikasi : Mengkomunikasikan aspirasi dan inisiatif', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (130, 'Kolaborasi : Berkolaborasi dengan unit kerja terkait', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (131, 'Pendidikan kepada pasien dan keluarga : tentang apa yang harus diketahui', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (132, 'Kompetensi profesional', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (133, 'Memahami uraian tugas profesinya', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (134, 'Pelaksanan SPO : memahami dan melaksanakan SPO sesuai bidang', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (135, 'Saling menghargai  : dalam tim pemberi asuhan', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (136, 'Menerapkan/bersikap etik dalam menjalankan profesi', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (137, 'Pendokumentasian kegiatan profesionalnya', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (138, 'Monitoring dan evaluasi berdasarkan dokumentasi', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (139, 'Identifikasi pasien : tepat dan benar', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (140, 'Memahami dan melaksanakan komunikasi efektif  :  dengan pasien dan keluarga', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (141, 'Menerapkan pencegahan resiko jatuh', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (142, 'Ketepatan : dalam waktu dan peayanan', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (143, 'Kepatuhan cuci tangan : sesuai prosedur', 'Profesi', 3, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (144, 'Wawasan keislaman : Mampu menjelaskan materi - materi ke-islaman', 'Ke-islaman', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (145, 'Praktik ibadah : Mampu Mempraktikkan ibadah praktis sesuai Tarjih Muhammadiyah', 'Ke-islaman', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (146, 'Bacaan Al-Qur\'an : Baik dalam membaca Al-Qur\'an sesuai Tajwid', 'Ke-islaman', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (147, 'Hafalan Al-Qur\'an: Baik dalam menghafal surat-surat Juz Amma sesuai Standart', 'Ke-islaman', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (148, 'Wawasan Ke-muhammadiyahan : baik dalam pemahaman wawasan ke-muhammadiyahan', 'Ke-muhammadiyahan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (149, 'Keaktifan kajian RSU Muhammadiyah Metro', 'Ke-muhammadiyahan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (150, 'Keaktifan di Persyarikatan dan Ortom', 'Ke-muhammadiyahan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (151, 'Disiplin : Kehadiran kerja tepat waktu', 'Sikap Kerja', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (152, 'Dedikasi : dalam melaksanakan kepentingan dinas', 'Sikap Kerja', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (153, 'Kerja sama : dengan orang lain/kelompok dan berperan aktif', 'Sikap Kerja', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (154, 'Komunikasi : Mengkomunikasikan aspirasi & inisiatif', 'Sikap Kerja', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (155, 'Melaksanakan pengkajian pasien pengkajian biopsikosial dan keagamaan', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (156, 'Identifikasi Keperawatan pasien : meliputi data dan dignosa', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (157, 'Merencanakan askep pasien : merencanakan dan menentukan askep lengkap, baik secara intervensinya secara keseluruhan', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (158, 'Membantu aktifitas pasien : melakukan dan memfasilitasi ADL pasien', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (159, 'Intervensi spesifikasi keperawatan dan terapi sesuai kondisi pasien', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (160, 'Evaluasi asuhan keperawatan', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (161, 'Membina hubungan pasien dan keluarga', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (162, 'Komunikasi : Mengkomunikasikan aspirasi dan inisiatif', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (163, 'Kolaborasi : Berkolaborasi dengan unit kerja terkait', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (164, 'Pendidikan kepada pasien dan keluarga : tentang apa yang harus diketahui', 'Kinerja Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (165, 'Pelaksanaan SPO : persiapan pekerjaan dan sistematika kerja sesuai dengan SPO', 'Mutu Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (166, 'Pemahaman pasien sesuai edukasi perawat', 'Mutu Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (167, 'Pengkajian pasien resiko jatuh', 'Mutu Pelayanan', 2, 'tahunan');
INSERT INTO `aspek` (`id`, `nama`, `kategori`, `bagian_id`, `tipe`) VALUES (168, 'Kesalahan pemberian obat : sesuai prosedur 6 benar serta pelaporannya', 'Mutu Pelayanan', 2, 'tahunan');
