INSERT INTO 
	`formasi` (`id`, `nama`, `created_at`, `updated_at`) 
VALUES 
	(1, 'Analis', NULL, NULL),
	(2, 'Apoteker', NULL, NULL),
	(3, 'Asisten Apoteker', NULL, NULL),
	(4, 'Bidan', NULL, NULL),
	(5, 'Bina Rohani', NULL, NULL),
	(38, 'Bindatra', NULL, NULL),
	(6, 'BPJS Center', NULL, NULL),
	(7, 'Cleaning Service', NULL, NULL),
	(8, 'Customer Service', NULL, NULL),
	(9, 'Dokter Umum', NULL, NULL),
	(11, 'Fisioterapis', NULL, NULL),
	(12, 'Juru Masak', NULL, NULL),
	(10, 'Juru Mudi', NULL, NULL),
	(13, 'Juru Racik', NULL, NULL),
	(14, 'Kasir', NULL, NULL),
	(15, 'Keuangan', NULL, NULL),
	(16, 'Loundry dan CSSD', NULL, NULL),
	(17, 'Pengantar Orang Sakit', NULL, NULL),
	(18, 'Perawat', NULL, NULL),
	(19, 'Perawat Gigi', NULL, NULL),
	(20, 'Pramusaji', NULL, NULL),
	(21, 'Radiografer', NULL, NULL),
	(22, 'Rekam Medis', NULL, NULL),
	(23, 'Rumah Tangga', NULL, NULL),
	(24, 'Sanitarian', NULL, NULL),
	(25, 'Satpam', NULL, NULL),
	(26, 'Staf  Pencitraan', NULL, NULL),
	(39, 'Staf Administrasi', NULL, NULL),
	(43, 'Staf Akuntansi', NULL, NULL),
	(42, 'Staf CSSD', NULL, NULL),
	(28, 'Staf Filling', NULL, NULL),
	(29, 'Staf IPSRS', NULL, NULL),
	(30, 'Staf IT', NULL, NULL),
	(41, 'Staf Kesling', NULL, NULL),
	(31, 'Staf Keuangan', NULL, NULL),
	(27, 'Staf Klaim Asuransi', NULL, NULL),
	(40, 'Staf Logistik', NULL, NULL),
	(32, 'Staf Loundry', NULL, NULL),
	(33, 'Staf Pendaftaran', NULL, NULL),
	(44, 'Staf Perpajakan', NULL, NULL),
	(34, 'Staf Tata Usaha & Personalia', NULL, NULL),
	(35, 'Teknisi', NULL, NULL),
	(36, 'Teknisi Elektromedis', NULL, NULL),
	(37, 'Tenaga Gizi', NULL, NULL);
