INSERT INTO 
    `unit` (`id`, `nama`) 
VALUES 
    (1, 'Bagian Keuangan'),
    (2, 'Bagian Umum'),
    (3, 'Bindatra'),
    (4, 'BPJS'),
    (5, 'Instalasi Farmasi'),
    (6, 'Instalasi Fisioterapi'),
    (7, 'Instalasi Gizi'),
    (8, 'Instalasi Laboratorium'),
    (9, 'Instalasi Radiologi'),
    (10, 'Instalasi Rekam Medis'),
    (11, 'IPSRS'),
    (12, 'Kabid Keperawatan & Kebidanan'),
    (13, 'Komite PPNI'),
    (14, 'Ruang Arafah'),
    (15, 'Ruang Assalam'),
    (16, 'Ruang Assyifa/Perianatalogi'),
    (17, 'Ruang CSSD'),
    (18, 'Ruang Hasanah'),
    (19, 'Ruang ICU'),
    (20, 'Ruang Marwah'),
    (21, 'Ruang Mina'),
    (22, 'Ruang OK'),
    (23, 'Ruang Poliklinik'),
    (24, 'Ruang Shafa'),
    (25, 'Ruang UGD'),
    (26, 'Tata Usaha dan Personalia'),
    (27, 'MPP'),
    (28, 'Ruang Musdalifah');
